// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ewiaobscdfwvjwnhjzmd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV3aWFvYnNjZGZ3dmp3bmhqem1kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg5ODg1ODEsImV4cCI6MjA4NDU2NDU4MX0.oAXEmChNFjWBGN5klKsimRrHM6uFAw-fGTk0BtVr5jI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});